### ISSUE TITLE
Conflict with WPML not loading all locations

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#102]
This has been reported twice in the forums - 
http://support.simplemap-plugin.com/discussions/problems/2570-missing-listings
(edit: first link not working - Arnaud)
http://support.simplemap-plugin.com/discussions/questions/1401-issue-adding-new-locations

I have been able to replicate this on my local test site.  I have traced it back to v2.4.9 of SimpleMap.  

When WPML is active, locations don't load either at all or only some load.  On my test site, no locations load.

**Comment by michaeltorbert** [comment]
@arnaudbroes Can you determine which commit caused this to break?

**Comment by arnaudbroes** [comment]
Not sure if I'm able to test this.
All versions below 2.4.10.1 don't have the Google API option and can't load Google Maps so I can't check the results.
@michaeltorbert

**Comment by michaeltorbert** [comment]
I'll see if I can write a quick plugin that adds the API key to older versions.

**Comment by arnaudbroes** [comment]
Ok cool. :-)

**Comment by michaeltorbert** [comment]
@arnaudbroes Ok so it doesn't look like that's something I can easily write an add-on plugin for... you may need to just manually add the api key code back in to what you're testing...

https://github.com/semperfiwebdesign/simplemap/commit/2004d4a21cfc14f5eaf1895d387e5fa0c6641e04

https://github.com/semperfiwebdesign/simplemap/commit/2cd8ded4a570b49cce019a4e961cae1e3b7c7159

**Comment by arnaudbroes** [comment]
@michaeltorbert Thanks that works for me. Tried it before but didn't know the exact changes to make it work.

**Comment by arnaudbroes** [comment]
So I tried adding the API manually to different .zips with commits but ran into a lot of errors.
However I'm thinking the problem has either something to do with this commit
https://github.com/semperfiwebdesign/simplemap/commit/b88f93615e691e719de1de311846ae062d1bd01d
or this commit
https://github.com/semperfiwebdesign/simplemap/commit/af36f2fef9d14e7da0a3143566a6a522e2a693d0

**Comment by arnaudbroes** [comment]
@michaeltorbert 
Just found out that the bug was introduced by commit b88f936.

**Comment by arnaudbroes** [comment]
@wpsmort Looks like 2.4.10 works but not 2.4.10.1, but you traced this back to 2.4.9 Steve?

**Comment by arnaudbroes** [comment]
This commit broke it:
https://github.com/arnaudbroes/simplemap/commit/b88f93615e691e719de1de311846ae062d1bd01d

![image](https://cloud.githubusercontent.com/assets/18156697/22172331/10b0a3de-dfa4-11e6-8826-58228f56a8f1.png)

Locations that are added AFTER wpml is installed do not show up. Earlier ones do.
Once this option is activated, locations reappear on the map.

![image](https://cloud.githubusercontent.com/assets/18156697/22172328/fb6c9c4e-dfa3-11e6-84bc-6bd75d4c2475.png)

**Comment by michaeltorbert** [comment]
Since this can be "fixed" with the checkbox, let's punt this for now.

**Comment by arnaudbroes** [comment]
I can confirm this is fixed.

Users have to go through the WPML configuration procedure first though, otherwise not a single location will show up (whether they are added before or after WMPL was activated does not matter).

**Comment by wpsmort** [comment]
I have also confirmed that this is fixed as long as you click Save under WPML > Languages.  I believe we can close this issue but first I want to test this on the latest customer that reported the problem.  I'm just waiting to get access to their site.
