### ISSUE TITLE
Bug report: Remove all data from the database doesn't work

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/simplemap#105]
"clicking on “Clicking this link will remove all data from the database.” and then clicking OK on the popup does not remove anything from the database as all my settings were still present after deleting and installing a clean version of the plugin to try and elminate the error."

Reported here: https://wordpress.org/support/topic/fatal-error-2139/#post-8215368

**Comment by michaeltorbert** [comment]
I've confirmed that the link to delete locations (CPT entries) only works, but the link to remove all data does nothing.

**Comment by wpsmort** [comment]
This is tested and is working fine.  Both links were tested and both are good.
