### ISSUE TITLE
Premium Support? Custom Markers?

### ISSUE THREAD

**Issue by jesspritchard** [semperfiwebdesign/simplemap#106]
Hi Team,

I know this isn't the correct place to send this message however I tried contacting you through your online contact form and have not heard back.

I recently purchased the Premium Support through your website however it was linked to the live domain but the website is currently only in development and not live. How can I access the Premium Support so that I can do Custom Markers without the site being live?

Is there an email address I can forward my enquiry onto?

Thanks,
Jess

**Comment by wpsmort** [comment]
We responded to your email on October 6th. Please email us if you need anything else.
