### ISSUE TITLE
Shortcode attribute that allows user to disable scroll wheel and dragging

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/simplemap#11]
Shortcode attribute that allows user to disable scroll wheel and dragging - 
also we can add this feature within the backend UI

**Comment by wpsmort** [comment]
This is tested and is good.  Needs a code review.  The shortcode attributes are:

To enable:
draggable='1' 
scrollwheel='1'

To disable:
draggable='0' 
scrollwheel='0'

**Comment by wpsmort** [comment]
This is tested and is good.
