### ISSUE TITLE
Change WP requirement to 3.0

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/simplemap#112]
We claim 2.8 as the requirement, but it's really 3.0.

**Comment by wpsmort** [comment]
This is confirmed in the readme.

**Comment by wpsmort** [comment]
@michaeltorbert: I think we should change this to require WP v3.3 or later.  I tested with old versions of WP and this was the first version where I got the plugin to work properly.  I can make this change in the readme.txt file if you agree.
