### ISSUE TITLE
Remove extra code defining custom table name constants

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/simplemap#114]
I'm pretty sure we haven't used custom tables in years.

**Comment by michaeltorbert** [comment]
For testing, we should activate every single thing in the plugin, add content in every way, and verify that a) nothing breaks, and b) no custom tables are created.

**Comment by wpsmort** [comment]
@michaeltorbert I have tested everything and only found two issues (#141 and #143) which should not affect this issue.  I believe this issue can be closed.
