### ISSUE TITLE
Manually entered coordinates get changed on save

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#117]
First reported here - http://support.simplemap-plugin.com/discussions/problems/2600-issue-with-longlat-entry

When you manually enter the coordinates in a location then the coordinates get changed upon updating the post.

Tested with these coordinates - 38.946057 / -91.9390670

**Comment by wpsmort** [comment]
@stanislavsa:  Were you able to replicate this bug before you made your code changes?  If so, how did you replicate it.  I've been unable to replicate the initial bug.  With version 2.4.10.1 I was able to change coordinates and they would save.

**Comment by michaeltorbert** [comment]
Looks good to me.

**Comment by wpsmort** [comment]
This is tested and is good. I tested with these coordinates - 38.946057 / -91.9390670
