### ISSUE TITLE
PHP notices when completing an import of locations

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#122]
These PHP notices appeared whilst testing #8.  They are not new.

Notice: Undefined variable: term in /simplemap/classes/import-export.php on line 480
Notice: Trying to get property of non-object in /simplemap/classes/import-export.php on line 482

**Comment by michaeltorbert** [comment]
I think fixing #8 fixed this one.

**Comment by wpsmort** [comment]
I have confirmed that these are fixed.
