### ISSUE TITLE
New description for SimpleMap 

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/simplemap#124]
SimpleMap also needs a new description (max. 15 words).

"SimpleMap is a convenient international store locator plugin for WordPress that uses Google Maps."
"SimpleMap is a store locator that uses Google Maps to display information on your site."
"SimpleMap is a store locator that uses Google to display information directly on your site."

Any suggestions?

**Comment by michaeltorbert** [comment]
Easy to use Store Locator plugin (supports international stores) using Google Maps?

**Comment by arnaudbroes** [comment]
Sounds good to me. The "SimpleMap is..." part doesn't have to be in there.

**Comment by arnaudbroes** [comment]
*didn't mean to close - misclick
