### ISSUE TITLE
Add theming docs to the website

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/simplemap#126]
I've removed the following from the readme for #121, so at some point it should be added to the website or someplace we're going to put documentation.

`Making Your Own Theme
To upload your own SimpleMap theme, make a directory in your plugins folder called simplemap-styles. Upload your theme's CSS file here.

To give it a name that shows up in the Theme drop-down menu (instead of the filename), use the following markup at the beginning of the CSS file:

/*
Theme Name: YOUR THEME NAME HERE
*/`

**Comment by wpsmort** [comment]
I've added documentation for this here - http://simplemap-plugin.com/documentation/theming-guide/
