### ISSUE TITLE
Signup Now takes you to same page

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/simplemap#128]
If you're on the Premium Support page in the plugin, clicking "Signup Now" takes you to the same page. Is it supposed to take you to http://simplemap-plugin.com/buy-now/ or am I missing something?

**Comment by michaeltorbert** [comment]
Looks like it used to take you to PayPal. We need to see when that changed.

**Comment by arnaudbroes** [comment]
This commit broke it:
https://github.com/semperfiwebdesign/simplemap/commit/8ee7bf4b8894fe1550f57ed9be6b9305dbff0042

![image](https://cloud.githubusercontent.com/assets/18156697/22169134/20f3f7aa-df72-11e6-9973-4f2bfccc1515.png)

**Comment by wpsmort** [comment]
I have tested all PayPal links and confirmed that they all work.
