### ISSUE TITLE
Importing hierarchical categories doesn't work

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#131]
When you export from an existing site that has locations in hierarchical categories and then import that into a new site, the categories all become top level categories with no hierarchy.  

I tested this in v2.4.8 and it didn't work in that version.  It's possible that this never worked.  We should test back through old versions and see if we ever supported importing of hierarchical categories.

This was identified whilst testing #98.

**Comment by wpsmort** [comment]
@arnaudbroes Do you want to have a go at testing this.  Let me know if you need my help.  

If you set up some hierarchical Location categories and add some locations to them and then export all locations, delete your locations by using the "remove all locations" link on the General Options screen and then import from your export file.

**Comment by michaeltorbert** [comment]
There should also be testing done with older version of WP... I wonder if the 4.4 changes did it.
@arnaudbroes You may want to keep a spreadsheet of what versions of SimpleMap have been tested with what versions of WordPress

**Comment by wpsmort** [comment]
@michaeltorbert I tested with an old back of simplemap-plugin.com from January 2013 which was running WordPress v3.5 and SimpleMap v2.4.5 and confirmed that this did not work then.

**Comment by arnaudbroes** [comment]
I tested this with WordPress v3.3.1, SimpleMap 2.4.4 and some newer releases of WP and SM, did not work.

**Comment by wpsmort** [comment]
This may actually have never worked because when I look at the export file there's nothing to distinguish a sub-category.  All categories show as a comma delimited list regardless of hierarchy, i.e.

Business, Personal, Family Sub-category

We need to identify a way of denoting category structure in our importer/exporter.  For example, the WooCommerce CSV importer uses this format:

Parent Category > Child Category

**Comment by contactashish13** [comment]
@wpsmort @michaeltorbert PR: https://github.com/contactashish13/simplemap/pull/1

I'm using | (pipe) to separate the parent and child category. I hope that's ok.

Also, I see that travis is not integrated so I will have to wait for your comments on whether I've adhered to the coding standards or not.

**Comment by michaeltorbert** [comment]
In the interest in keeping everything together, Ashish's earlier remarks:

> Ok. So I believe the problem is two-fold

1) While exporting, we are only exporting the term name without the parent. Maybe we should export it in the format "parent term/child term" or add a separate column for the parent
2) While importing, we set hierarchical = false but it should be true and the parent should also be provided when using wp_insert_term

**Comment by wpsmort** [comment]
@contactashish13:  I've tested this and found that it only supports two levels - Parent Category | Sub Category.  This should support any number of levels, for example:

Parent | Sub Cat | Sub Sub Cat | etc...

**Comment by wpsmort** [comment]
I've closed pull request 210

**Comment by contactashish13** [comment]
@wpsmort I've added support for N levels. PR: https://github.com/semperfiwebdesign/simplemap/pull/218

**Comment by wpsmort** [comment]
This is tested and is good.  I tested up to 5 levels deep for sub categories, i.e.

Level 1 | Level 2 | Level 3 | Level 4 | Level 5

**Comment by wpsmort** [comment]
This is tested and is good.
