### ISSUE TITLE
Import screen doesn't fit within Dashboard space

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/simplemap#133]
As seen here:

![image](https://cloud.githubusercontent.com/assets/18156697/22170361/e787b316-df7c-11e6-8fd8-56e65cb7e33d.png)

**Not responsive as well.

**Comment by michaeltorbert** [comment]
@arnaudbroes  Yeah this needs to be completely redone for desktop too

**Comment by arnaudbroes** [comment]
Yep I meant desktop, already changed title.

**Comment by wpsmort** [comment]
This is a duplicate of #125
