### ISSUE TITLE
Description doesn't show HTML lists

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/simplemap#138]
![image](https://cloud.githubusercontent.com/assets/18156697/22216743/912e549a-e1a0-11e6-9d27-15314cd1cd4d.png)

**Comment by arnaudbroes** [comment]
Noticed working example here:
https://wordpress.org/plugins/simplemap/screenshots/
![image](https://cloud.githubusercontent.com/assets/18156697/22217541/aafb5ffa-e1a3-11e6-848a-fa0d19a6bf63.png)

**Comment by wpsmort** [comment]
This issue is fixed and tested.
