### ISSUE TITLE
Thumbnail map broken on the single location

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#141]
It looks like we broken the small thumbnail map on the single location page.  See screenshot:

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/22218070/5d73a560-e173-11e6-9dd5-d0ff5a30e27d.png)

This works in the current live version. There are some JS errors in the browser console and some PHP notices in the debug log that may be related.

**Comment by wpsmort** [comment]
@arnaudbroes Can you track down which commit broke this.  Let me know if you have questions.

**Comment by wpsmort** [comment]
Here are the PHP Notices:

Undefined index: panControl in /simplemap/classes/maps.php on line 235
Undefined index: zoomControl in /simplemap/classes/maps.php on line 236
Undefined index: scaleControl in /simplemap/classes/maps.php on line 237
Undefined index: streetViewControl in /simplemap/classes/maps.php on line 238
Undefined index: mapTypeControl in /simplemap/classes/maps.php on line 239

**Comment by arnaudbroes** [comment]
@wpsmort 
This is working for me till the most recent commit.
Your browser says multiple API keys are embedded in the code.
Any idea what may be causing that?

**Comment by michaeltorbert** [comment]
<img width="928" alt="screen shot 2017-01-23 at 2 38 12 pm" src="https://cloud.githubusercontent.com/assets/17364998/22219686/bc9ff768-e179-11e6-88ca-6113dec9292b.png">

**Comment by arnaudbroes** [comment]
I'll take a look if earlier commits/versions also outputted the API error.

**Comment by arnaudbroes** [comment]
@wpsmort @michaeltorbert 
This error has probably been there since the permalink ability (v2.4) has been added.
I could only test 2.4.4 since the previous versions are not available on WordPress.org.

**Comment by wpsmort** [comment]
I cannot replicate this on my other test site.  It only happens on one site.  I'm trying a new install of WP to see if I can replicate it.

**Comment by wpsmort** [comment]
I have found the cause of this issue is because we have two Google Maps API calls in the HEAD section of the iframe code that generates the small map.  One call is included in wp_head() and the other is explicitly defined before the closing head tag.  

The first call in wp_head() is only included when you do not have a page ID under Map Page IDs.  This is because we're loading our scripts on the singular location page, whereas if there is a page ID specified under Map Page IDs then we don't load our scripts in wp_head() in the iframe.  I believe wp_head() should be removed from the iframe code.

The second call is the correct call but it's missing the Google Maps API Key so the map won't load.  We need to adjust this code to include the Google Maps API Key. 

I have opened a new issue #143 to address the fact that we are not loading scripts on the singular location page.

**Comment by wpsmort** [comment]
During testing today I found that the thumbnail map shows fine if you use the external (Live) link to a Pressmatic site so this is definitely a local Pressmatic issue.

**Comment by wpsmort** [comment]
@michaeltorbert I believe I have added code to fix this issue.  I've tested on multiple sites where this was broken and it is certainly fixed now with no console errors.  This does need a code review by you to make sure I didn't do something dumb.

**Comment by michaeltorbert** [comment]
@wpsmort Related to #175, now the API key is showing up twice. Were both of these lines (even without the api key) showing up previously?

**Comment by wpsmort** [comment]
This is now fixed and tested.
