### ISSUE TITLE
Everything Else button in Premium Support menu broken

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/simplemap#142]
This button doesn't seem to do anything.
I believe that field has been deleted a long time ago.

Can you check this?

![image](https://cloud.githubusercontent.com/assets/18156697/22218466/3a666ede-e1a7-11e6-95b6-d061bd84e611.png)

**Comment by wpsmort** [comment]
I've removed this link as it is no longer needed.
