### ISSUE TITLE
Need to enqueue scripts on singular location page

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#143]
Whilst troubleshooting #141 I found that we're not enqueuing scripts on the singular location page if a page ID has been entered in the Map Page IDs field under General Option.  You can see this because the stylesheet and Google Maps API call are not output in the source code unless you remove the Map Page IDs.

The code is in classes/simplemap.php on line 624 where we enqueue scripts.   We need to add code that always enqueues the scripts on the singular location pages.

We need to output the call to the stylesheet but not the call to the Google Maps API or it will cause a conflict with the fix for #141 (i.e. there will be two calls to the Google Maps API, one in the head of the singular locations page and one in the head of the iframe code).

**Comment by wpsmort** [comment]
@michaeltorbert I've added what I believe is the correct conditional to the enqueue scripts function and tested that this works.  This needs a code review to make sure it's good.

**Comment by michaeltorbert** [comment]
This may be related to #175

**Comment by wpsmort** [comment]
This is now working correctly.
