### ISSUE TITLE
Make API key nag more prominent

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/simplemap#146]
Since the API key is required, we should make it persistent on every page in wp-admin.

**Comment by wpsmort** [comment]
This is tested and is good.

@michaeltorbert Should we make the CSS class for this notice or error?  It did have a class of error which meant the banner had a red left border.  But now it has a class of notice which means the border is blue.

**Comment by wpsmort** [comment]
The change to the class is now done and tested.
