### ISSUE TITLE
PHP notices when you save the widget

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#151]
When you go to Appearance > Widgets and save the settings in the SimpleMap widget, these PHP notices occur:

PHP Notice:  Undefined index: show_address in /simplemap/classes/widgets.php on line 205
PHP Notice:  Undefined index: show_city in /simplemap/classes/widgets.php on line 206
PHP Notice:  Undefined index: show_state in /simplemap/classes/widgets.php on line 207
PHP Notice:  Undefined index: show_zip in /simplemap/classes/widgets.php on line 208
PHP Notice:  Undefined index: show_distance in /simplemap/classes/widgets.php on line 209
PHP Notice:  Undefined index: default_lat in /simplemap/classes/widgets.php on line 210
PHP Notice:  Undefined index: default_lng in /simplemap/classes/widgets.php on line 211
PHP Notice:  Undefined index: show_categories in /simplemap/classes/widgets.php on line 218
PHP Notice:  Undefined index: categories in /simplemap/classes/widgets.php on line 219
PHP Notice:  Undefined index: show_tags in/simplemap/classes/widgets.php on line 218
HP Notice:  Undefined index: tags in /simplemap/classes/widgets.php on line 219

**Comment by wpsmort** [comment]
I tested pull request 222 and found a bug where clicking Save on the widget resets the entry in the SimpleMap Page or Post ID field back to 1.

**Comment by wpsmort** [comment]
This is tested and is good.  The pull request needs code review.

**Comment by michaeltorbert** [comment]
Looks ok to me, especially after #223

**Comment by wpsmort** [comment]
This is tested and is good.
