### ISSUE TITLE
If it can't find the FT server, we should bail more gracefully

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/simplemap#152]
WP_Error crashes the options page load via ft-ps-client.php on line 105 if it can't find the FT server

**Comment by michaeltorbert** [comment]
For testing, disconnect from the internet, and when you hit the simplemap options page, you should get an error (about WP_Error). This commit should fix it.

**Comment by wpsmort** [comment]
This is tested and confirmed fixed.
