### ISSUE TITLE
Google Maps API warning: SensorNotRequired

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#169]
On single location page is the following JS warning:

Google Maps API warning: SensorNotRequired

**Comment by wpsmort** [comment]
@michaeltorbert I've removed the parameter from the URL and tested to confirm that the warning has gone away.  It just needs code review by you to make sure I didn't do something dumb.

**Comment by wpsmort** [comment]
See also #145

**Comment by michaeltorbert** [comment]
This has been tested and is fixed.
