### ISSUE TITLE
Single location map is missing map controls

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#170]
The map on the single location page doesn't have controls for zoom, pan, scale, street view, or map type view.  You also can't drag the map.  

There are undefined index notices showing in the debug log for this:

PHP Notice:  Undefined index: panControl in /simplemap/classes/maps.php on line 238
PHP Notice:  Undefined index: zoomControl in /simplemap/classes/maps.php on line 239
PHP Notice:  Undefined index: scaleControl in /simplemap/classes/maps.php on line 240
PHP Notice:  Undefined index: streetViewControl in /simplemap/classes/maps.php on line 241
PHP Notice:  Undefined index: mapTypeControl in /simplemap/classes/maps.php on line 242

**Comment by wpsmort** [comment]
@michaeltorbert This is done and tested but needs a code review to make sure I didn't do anything dumb.

**Comment by michaeltorbert** [comment]
This is good.
