### ISSUE TITLE
Single location page - js error - api key included too many times

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/simplemap#175]
<img width="963" alt="screen shot 2017-02-27 at 8 22 39 pm" src="https://cloud.githubusercontent.com/assets/17364998/23387441/8caa9a64-fd2a-11e6-9c2c-3e8ebb458e85.png">

**Comment by michaeltorbert** [comment]
This may be a dupe.

**Comment by wpsmort** [comment]
@michaeltorbert This is a dupe of #141 but I've not been able to replicate this since my last commit under #141

**Comment by wpsmort** [comment]
This is now fixed and tested.
