### ISSUE TITLE
single location map - various javascript errors

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/simplemap#176]
<img width="492" alt="screen shot 2017-02-27 at 8 23 46 pm" src="https://cloud.githubusercontent.com/assets/17364998/23387490/cdc8313c-fd2a-11e6-93fc-110bf70b68a3.png">

**Comment by wpsmort** [comment]
@michaeltorbert I'm unable to replicate these console errors on either a live site or my local dev site.

**Comment by wpsmort** [comment]
This is now fixed and tested.
