### ISSUE TITLE
Incorrect textdomain in code

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#189]
Reported by Ben Besselink via email:

there is an error in your code. the textdomain is "SimpleMap" but you have several time called it "simplemap" in _e() and __() commands. so the translation does not work. and i have to fix it on every update you release.
best regards

**Comment by RHEINWEB** [comment]
i've correct the textdomain in your code on github. but i can't upload the fully translated language files, so here they are:
[de_DE.mo](https://drive.google.com/open?id=0B2tdAe1pcgzPWTItUzgweGpHeG8)
[de_DE.po](https://drive.google.com/open?id=0B2tdAe1pcgzPcEdWSDlwckhVT1E)

**Comment by michaeltorbert** [comment]
@RHEINWEB Thank you, we'll review it shortly and commit it to the repo.
We're using the wordpress.org system for translations now, which can be submitted to https://translate.wordpress.org/projects/wp-plugins/simplemap

So for instance, German is https://translate.wordpress.org/locale/de/default/wp-plugins/simplemap

@arnaudbroes will be happy to fill you in on any other details regarding submitting translations

**Comment by arnaudbroes** [comment]
@RHEINWEB 

Hi Ben 

Thanks for submitting those language files!
As Michael mentioned, we are using the translate.wordpress.org platform right now for our locales:
https://translate.wordpress.org/projects/wp-plugins/simplemap
Soon we'll be starting on translating SimpleMap to a couple of major languages (including German).

Once that update is out a PTE will be able to upload that language file for German.
PTEs are so called Project Translation Editors, which can approve translated strings and correct them.
Currently we do not have a PTE for German (and AIOSEO) and we could definitely use one.

If you'd be interested in helping us out with keeping SimpleMaps or AIOSEO updated in German in the future, then please let us know. Don't feel obligated though. You can contact me here on GitHub or via abroes@semperfiwebdesign.com.

Thanks!

**Comment by michaeltorbert** [comment]
@RHEINWEB The textdomain simplemap is correct, not SimpleMap. The reason why SimpleMap works for you is because of the filename.
Translations should go to https://translate.wordpress.org/projects/wp-plugins/simplemap

**Comment by michaeltorbert** [comment]
Related to #200

**Comment by RHEINWEB** [comment]
Hello Michael,

what do you mean with "The reason why SimpleMap works for you is because of
the filename."? with "simplemap" the translation doesn't work for me. does
it work for you? why?

greetings
Ben Besselink

Mit freundlichen Grüßen




*Ben Besselink*
*CEO & Web Developer*

Lindenstr. 112
47798 Krefeld

Tel. +49 2151 3268124
Mobil +49 177 7183246
Fax +49 32221932338

info@rhein-web.com
www.rhein-web.com

USt-IdNr. DE306597551
Steuer-Nr. 117/5023/1582

2017-03-21 17:16 GMT+01:00 Michael Torbert <notifications@github.com>:

**Comment by michaeltorbert** [comment]
@RHEINWEB I've found the issue, and it will be resolved in the next version. However, translations should be submitted to https://translate.wordpress.org/projects/wp-plugins/simplemap, as we will no longer be supporting included files once we've finished the migration to the hosted translation system.
