### ISSUE TITLE
Add field for searching by location name

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/simplemap#19]
Added field for searching by name.

This should enable a user to search for the location name (i.e. the title of the location post).

**Comment by wpsmort** [comment]
This should have been in the code for SimpleMap v2.5

**Comment by wpsmort** [comment]
@stanislavsa I tested this but found that if you entered a pace name, a ZIP code and selected a distance that it would ignore the distance.  It also seemed to be matching on category and tag names.  So I could enter the name of a category in the place field and it would return locations in that category.

**Comment by stanislavsa** [comment]
The distance ignoring issue fixed.
Matching on category and tag names is in progress.

**Comment by wpsmort** [comment]
@stanislavsa I tested PR #241 and found that the behavior is now worse than before.  When I search for a place name with a ZIP code that has that location in then nothing is returned and the map jumps to a random place somewhere else.

**Comment by stanislavsa** [comment]
@wpsmort In earlier commit I added place name data to the 'address' parameter in the geocoder js function and in some cases it returns wrong results (latitude and longitude). So I removed that code.

**Comment by wpsmort** [comment]
This is tested and works fine.  This is now ready for code review.
