### ISSUE TITLE
Undefined index: language, post_translations

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#196]
Reported by a user here - https://wordpress.org/support/topic/php-notices-undefined-index-3/

I’m getting quite a few PHP Notices: Undefined index: language, post_translations in …/wp-content/plugins/simplemap/classes/simplemap.php on line 273

**Comment by michaeltorbert** [comment]
This is most likely related to the use of a translation plugin (probably WPML). No matter the settings, I can't seem to reproduce it.
If the user provides us with more information or access to his site we can reopen this.
