### ISSUE TITLE
Notice: Undefined index: map_type

### ISSUE THREAD

**Issue by EkoJr** [semperfiwebdesign/simplemap#198]
This might be the same issue that occurred before getting started, and it's just a notice with debug mode enabled. It also occurred on a fresh install. Note: Clears up after refreshing.

Steps to Error.
1. Install the plugin.
2. Activate Plugin.

A warning is then displayed at the top.

( ! ) Notice: Undefined index: map_type in simplemap\classes\simplemap.php on line 1811

Call Stack

1	0.0010	499448		{main}( )													...\plugins.php:0
2	0.0010	549840		require_once( 'C:\wamp64\www\EkoJR\wp-admin\admin.php' )	...\plugins.php:10
3	0.0010	565008		require_once( 'C:\wamp64\www\EkoJR\wp-load.php' )			...\admin.php:31
4	0.0020	577504		require_once( 'C:\wamp64\www\EkoJR\wp-config.php' )			...\wp-load.php:37
5	0.0020	685600		require_once( 'C:\wamp64\www\EkoJR\wp-settings.php' )		...\wp-config.php:89
6	0.2450	30215616	do_action( )												...\wp-settings.php:449
7	0.2450	30216024	WP_Hook->do_action( )										...\plugin.php:453
8	0.2450	30216056	WP_Hook->apply_filters( )									...\class-wp-hook.php:323
9	0.2550	30366560	Simple_Map->enqueue_backend_scripts_styles( )				...\class-wp-hook.php:298
10	0.2550	30366560	Simple_Map->get_options( )									...\simplemap.php:657

**Comment by wpsmort** [comment]
I tested this and was able to replicate it.  I tested all the way back to version 2.4.5 and this notice was present back then and in every version since then.

**Comment by michaeltorbert** [comment]
This was caused by old code we had migrating the map type from Google Maps V2 names to V3 names. I've just removed the code.

**Comment by wpsmort** [comment]
We agreed to remove this code as it's only applicable when updating from very old versions (7 years ago).  I've opened a new issue #214 for adding an updater class.

**Comment by wpsmort** [comment]
This is tested and is good.  There doesn't appear to be any problems associated with removing that code for map type.
