### ISSUE TITLE
Fix compatibility issue with WPML

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#2]
I received this email from Yuk at WPML:

We are currently retesting compatibility of your plugin with WPML.  We have found common issue related to showing locations from all languages.

Usually this can be easily fixed by adding 'suppress_filters' => false, to your post query.

Please take a look and fix this so I can send WPML an updated version of SimpleMap to test.

**Comment by michaeltorbert** [comment]
The query isn't a "post query" per se, it's in xml-search.php ( 92-134 ), there's not really a suppress_filters anyway so I'm not really sure what we should do here.

**Comment by michaeltorbert** [comment]
According to this link, direct queries bypass WPML's filters.
 https://wpml.org/forums/topic/manual-custom-post-type-query/

**Comment by michaeltorbert** [comment]
@wpsmort Looking through those links, it looks like if we're not using are regular WordPress query, we can include WPML stuff in the query instead, but I'm not sure of the exact details.

**Comment by michaeltorbert** [comment]
@wpsmort This mostly seems to work, at least for single locations, although you can't select the language on the map page... js conflict? because the map page isn't translated?

**Comment by michaeltorbert** [comment]
Ok the main map page should be working now

**Comment by wpsmort** [comment]
This is fixed if you're using WPML language format set to Language name added as a parameter but not if you use Different languages in directories or A different domain per language.  I have opened a new issue for this.
