### ISSUE TITLE
Add alternative(s) for geolocating addresses based on IP

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/simplemap#20]
Add alternative(s) for geolocating addresses based on IP

**Comment by wpsmort** [comment]
The service we use for IP geolocation has shut down - http://www.telize.com/

We urgently need to remove this option from the plugin.  Anyone currently using IP Address for Auto-Detect Location has a broken map which has resulted in a lot of support forum posts and emails.  

We eventually need to find a replacement free IP geolocation service.

**Comment by wpsmort** [comment]
These are the three services that WooCommerce uses:

'freegeoip'        => 'https://freegeoip.net/json/%s',
'telize'           => 'http://www.telize.com/geoip/%s',
'geoip-api.meteor' => 'http://geoip-api.meteor.com/lookup/%s

**Comment by michaeltorbert** [comment]
@wpsmort Can you verify this was fixed and released already?

**Comment by wpsmort** [comment]
This was fixed under #68 in version 2.4.9
