### ISSUE TITLE
Add customizable category icons add-on

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#204]
A potential premium Pro feature or add-on is to let users set icons for categories and have these display in the search form and in the location results and individual location pages.  The screenshot below shows how a major store implemented this.  

<img width="1056" alt="screen shot 2017-03-21 at 6 01 16 pm" src="https://cloud.githubusercontent.com/assets/17548525/24172989/a06c828c-0e60-11e7-93dc-9f23dd746baf.png">

**Comment by michaeltorbert** [comment]
Added to pro https://github.com/semperfiwebdesign/SimpleMap-Pro/issues/9
