### ISSUE TITLE
Add custom map markers add-on

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#205]
One of the most requested features from users is custom map markers.  We have code that we provide users for this.  The code can be found here - http://support.simplemap-plugin.com/kb/setup-installation/adding-custom-markers

This would make a good premium Pro add-on.

**Comment by michaeltorbert** [comment]
Added to the Pro repository https://github.com/semperfiwebdesign/SimpleMap-Pro/issues/7
