### ISSUE TITLE
Add integration with EDD Software Licensing add-on

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#208]
Integrate the EDD software licensing with SimpleMap and the automatic updater.  See the documentation and related articles at the end of this link - http://docs.easydigitaldownloads.com/article/381-software-licensing-usage-instructions

**Comment by michaeltorbert** [comment]
Added to pro https://github.com/semperfiwebdesign/SimpleMap-Pro/issues/8
