### ISSUE TITLE
Settings pages should go to edit.php instead of admin.php

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/simplemap#209]
edit.php?post_type=sm-location&page=????

**Comment by michaeltorbert** [comment]
For testing, we should make sure that none of the modified links are broken.

**Comment by wpsmort** [comment]
@michaeltorbert There was one link missed here, it's on line 2294 of classes/simplemap.php and is for the Premium Support link in the top right corner of the General Options screen (next to the Donate button).

**Comment by wpsmort** [comment]
I've made the change to the Premium Support link in the top right corner of the General Options screen and tested.  This just needs a final code review.

**Comment by michaeltorbert** [comment]
Looks good.
