### ISSUE TITLE
Translations not working unless you rename the PO file

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#216]
Reported by Piet Geerts by email today.

I tried to use the dutch translation with the .po and .mo files in the lang directory of the plugin. The translation wasn't working. In the files of your plugin I discovered that the filename for the translation files should be simplemap, but the files in the lang directory are named SimpleMap-nl_NL.po I changed them to the name listed in the code and it worked!

**Comment by wpsmort** [comment]
@arnaudbroes: Can you verify this please.  Note that Piet is suggesting that renaming the PO files from SimpleMap to simplemap (no camel case) fixes this.

**Comment by michaeltorbert** [comment]
Arnaud and I are already aware of this. I'll take this one.

**Comment by michaeltorbert** [comment]
I'm closing this since we're removing the lang directory in #283
