### ISSUE TITLE
"Signup now" button on Premium Support wp-admin menu page in the plugin broken

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/simplemap#219]

**Comment by wpsmort** [comment]
This is because we have Tenderapp set up in private mode so that you have to be invited to join.  When customers purchase SimpleMap they get access but others who haven't purchased cannot access without an invite from an admin.

**Comment by michaeltorbert** [comment]
The problem was that I was signed into the PayPal account. Apparently PayPal doesn't like you to buy your own product.
