### ISSUE TITLE
"Uncaught ReferenceError: google is not defined"

### ISSUE THREAD

**Issue by billerr** [semperfiwebdesign/simplemap#255]
Hi, I am experiencing the issue in the title on a WPML setup.
The site has 2 languages set-up on separate directories (Greek: / , English: /en ).
The SimpleMap loads perfectly on the GR version. On the EN version of the same page, nothing loads, and the console throws the error "Uncaught ReferenceError: google is not defined". I noticed that the "http://maps.googleapis.com/maps/api/js" resource only loads in the GR version, and not in the EN one - perhaps this might provide a clue.

You can see the 2 pages here:
- GR: http://www.dzine.gr/retailers/
- EN: http://www.dzine.gr/en/retailers/

In an effort to fix this before waiting for any plugin updates (as this is a live site and we need this fix ASAP), we tried editing the installation files according to the commit from issue #244. However, the problem still persists.

Any ideas? Let me know if I can provide any more info.

**Comment by EkoJr** [comment]
It appears the scripts for google aren't being added for the 'en' URL. The scripts should be similar to...

`<link rel='dns-prefetch' href='//maps.googleapis.com' />`
AND
`<script type='text/javascript' src='http://maps.googleapis.com/maps/api/js?...'></script>`

I might be able to expedite a fix for this. Also, thank you for letting us know about this.

**Comment by billerr** [comment]
Hi!
I found a solution (or is it a workaround?)
I needed to add the page ID of the 'en' page into the "Map Page IDs" fields. Now the checks work and the scripts load correctly.

**Comment by EkoJr** [comment]
I was able to get a good look, and it looks like you may be referring to this...

![issue-225-suspected-oversight](https://user-images.githubusercontent.com/2794445/30246159-9c0fc6f4-95a6-11e7-9264-805b4ebf2d52.png)

If so, that is a built in setting to control where scripts are loaded. It's to load on different pages for site optimization, but it seems there was an oversight with multilingual being separate pages as well. It's not exactly a bug, but I suppose it could be improved to catch this.

@wpsmort Would this be worth noting in an FAQ for multilingual pages?

**Comment by wpsmort** [comment]
@EkoJr I have updated the documentation with a note about this - http://simplemap-plugin.com/documentation/general-options/
