### ISSUE TITLE
Info Window not showing on map

### ISSUE THREAD

**Issue by jesspritchard** [semperfiwebdesign/simplemap#258]
Hi All,

This is a long shot, but I have a website that has a heavily customised version of the SimpleMap plugin (no idea what version, but it doesn't have an option to add an API key in the admin area so that would give you an idea of how old it really is).

All of a sudden the InfoWindow on the map doesn't show - you see the bottom arrow, and the X button but not the actual box or any content. It's also not in the markup.

I've uploaded the newest version of the plugin to the site and it works fine so I know it's due to the outdated plugin but I am struggling to copy over the customisations previously made. I'm not a PHP developer and didn't make the original edits so I was wondering / hoping someone might have prior knowledge of why the info window might've suddenly disappeared?

Thanks,
Jess

**Comment by wpsmort** [comment]
We only provide support for unmodified versions of our plugin.
