### ISSUE TITLE
Theme no longer working on https://simplemap-plugin.com/

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/simplemap#273]
![image](https://user-images.githubusercontent.com/18156697/45927842-0eac9580-bf3a-11e8-8cc8-c2c4fc3743d3.png)

**Comment by michaeltorbert** [comment]
Is this on mobile? Do we know if it was ever working on mobile?
It works fine for me on the computer.

**Comment by arnaudbroes** [comment]
@michaeltorbert doesn't work for me on PC either, but I just found out it's due to a browser security issue (they consider the site unsafe). Perhaps something to do with the HTTPS certificate?

**Comment by wpsmort** [comment]
This is now fixed.  It was because some stylesheets weren't loading over SSL but I fixed this using the SSL Insecure Content plugin that was already installed on the site.  Arnaud confirmed the site is working for him now and I tested in various browsers.

**Comment by arnaudbroes** [comment]
@wpsmort only the homepage seems to be working correctly on my end; if I go to any of the other pages, then the CSS doesn't render. Can you confirm this?

**Comment by wpsmort** [comment]
@arnaudbroes Please test in all browsers now as it should be working fine now.

**Comment by arnaudbroes** [comment]
@wpsmort 
![image](https://user-images.githubusercontent.com/18156697/51563799-accf4e80-1e8d-11e9-8f35-9ea1f4f37f85.png)

**Comment by wpsmort** [comment]
@arnaudbroes I believe this is a caching issue.  Please try now.

**Comment by arnaudbroes** [comment]
@wpsmort good now. Server cache I'm guessing?
