### ISSUE TITLE
Locations are no longer geocoded when inserted

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#277]
Reported by Marco S. by email on 10/18/2018.

When you import locations into SimpleMap using the CSV file, locations should get geocode (longitude and latitude added) upon import.  However, when you edit an imported location the longitude and latitude fields are empty.

**Comment by wpsmort** [comment]
Also reported here - http://support.simplemap-plugin.com/discussions/problems/2852-batch-geo-coding-no-longer-seems-to-work

**Comment by wpsmort** [comment]
Reported again by Adam Taylor by email.

**Comment by arnaudbroes** [comment]
Reported again by J. Burke by e-mail.

**Comment by arnaudbroes** [comment]
Here's what Ben said so far:
```
It's looking like is an issue with the missing Country param.

I've tried a few workarounds with no success. Even if the fallback was the default country, it is still problematic if the address does reside in the country. Plus, Google requires that country param.
```

**Comment by wpsmort** [comment]
Reported again here - http://support.simplemap-plugin.com/discussions/problems/2880-csv-feature-doesnt-automatically-create-lat-long-information

**Comment by arnaudbroes** [comment]
This also happens when adding a new location through the backend, so it's a general issue, and not specific to the importer/exporter.

**Comment by wpsmort** [comment]
Reported by Bob Thornton by email

**Comment by wpsmort** [comment]
@arnaudbroes Can you look and see if you can fix the geocoding of locations on import as that is part of this issue.

**Comment by arnaudbroes** [comment]
@wpsmort it does not; only after updating each location. I'll check where the API call is happening and fix it.
