### ISSUE TITLE
SImplemap not loading any locations

### ISSUE THREAD

**Issue by dharlan2728** [semperfiwebdesign/simplemap#278]
All of the sudden, simplemap is not longer loading any of the locations. Even when I type in a zip code, nothing shows up. http://intercorpusa.com/home/find-a-distributor/

Search button seems unresponsive.

**Comment by wpsmort** [comment]
This is a development repository and not a support forum.  Premium support is available for purchase here http://simplemap-plugin.com/ and by contacting us here https://simplemap-plugin.com/contact/

**Comment by dharlan2728** [comment]
I already purchased premium support, but no one responded to my issue. The link you gave me is how I got here. Do you have an e-mail address that support questions can be sent to?

**Comment by wpsmort** [comment]
We've not received any email from you.  Please use the contact form to send us a message and we'll respond.

**Comment by dharlan2728** [comment]
<img width="603" alt="screen shot 2018-12-07 at 9 42 46 am" src="https://user-images.githubusercontent.com/45696005/49663762-800dc780-fa04-11e8-9feb-f2bd0d6b15e3.png">

None of the contact links work on the link you sent me. See attachment.

**Comment by wpsmort** [comment]
I just tested the form and it's working fine.  Please try a different browser as our site and contact form are working.  Please select Other in the drop down on the contact form.

**Comment by dharlan2728** [comment]
The only e-mail address that I can find for you is info@fullthrottledevelopment.com, which I have sent e-mails to. If this is not the correct address can you please provide one to me at david@intercorpusa.com? I have tried opening your contact form on Windows 10 - Chrome, Edge as well as OSX - Chrome and Safari. Form does not work on either platform or any of the mentioned browsers.
