### ISSUE TITLE
Simple Map stopped working on our website??  not sure what to do . 2.5.0.1 version of simple maps is  We updated our app, our WP version is 5.0.1 we are on

### ISSUE THREAD

**Issue by Biolight1414** [semperfiwebdesign/simplemap#279]
Our simple map app is no longer working on our website http://www.biolighttechnologie.com  Please help us know what to do to get it working again.  thank you   770-540-5990

**Comment by wpsmort** [comment]
We have responded to your email.  This is a development repository and not a support forum.
