### ISSUE TITLE
Simple Map locater not working

### ISSUE THREAD

**Issue by mindypong** [semperfiwebdesign/simplemap#280]
Our simple map plugin has stopped working. http://www.clearwaterspas.com/dealers/ We are up to date, but when you enter information, and click "search" nothing happens.

**Comment by wpsmort** [comment]
@mindypong This is a development repository.  You can access support via the Premium Support widget in SimpleMap under SimpleMap > Premium Support.  Please note you will need a current support subscription which you can purchase here - https://simplemap-plugin.com/buy-now/

**Comment by mindypong** [comment]
Hello,

I renewed our license a few days ago, but it has not updated on our wordpress site yet and this feature is still not working. Can you please let me know when I might expect this to be updated on your end?

Thank you,

Mindy Pongpanik
mpongpanik@clearwaterspas.com<mailto:mpongpanik@clearwaterspas.com>
[cid:D38B173B-0614-4F46-B9B7-00AC7582207B@clearwaterspas.com]

On Jan 3, 2019, at 11:33 AM, wpsmort <notifications@github.com<mailto:notifications@github.com>> wrote:


@mindypong<https://github.com/mindypong> This is a development repository. You can access support via the Premium Support widget in SimpleMap under SimpleMap > Premium Support. Please note you will need a current support subscription which you can purchase here - https://simplemap-plugin.com/buy-now/

**Comment by wpsmort** [comment]
@mindypong Please contact us here https://simplemap-plugin.com/contact/.  Select Other as the reason for contact and please provide the PayPal transaction ID for your renewal payment.

**Comment by mindypong** [comment]
Ok I just did that.

Thank you.

Mindy Pongpanik
mpongpanik@clearwaterspas.com<mailto:mpongpanik@clearwaterspas.com>
[cid:D38B173B-0614-4F46-B9B7-00AC7582207B@clearwaterspas.com]

On Jan 14, 2019, at 10:56 AM, wpsmort <notifications@github.com<mailto:notifications@github.com>> wrote:


@mindypong<https://github.com/mindypong> Please contact us here https://simplemap-plugin.com/contact/. Select Other as the reason for contact and please provide the PayPal transaction ID for your renewal payment.
