### ISSUE TITLE
Premium Support button not working

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/simplemap#282]
This broke:

![image](https://user-images.githubusercontent.com/18156697/52332724-d3e45f00-29fb-11e9-80b7-17cd935df356.png)

**Comment by wpsmort** [comment]
@arnaudbroes What specifically broke?  I checked on a couple of sites and it's working fine for me.  It links correctly to the Premium Support sub menu item - /wp-admin/admin.php?page=simplemap-help

**Comment by arnaudbroes** [comment]
@wpsmort nevermind then, I thought that button was supposed to link to the support forum.
