### ISSUE TITLE
Locations not geocoded when API Key has application restrictions in place

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#287]
Reported by Jonathan Heslop by email.

When you use Application Restrictions to restrict your API key to either a website or IP address, locations do not get geocoded.

To reproduce this, follow the instructions in our documentation (https://simplemap-plugin.com/documentation/setting-up-google-maps-api-key/) to set up an API Key and apply Application Restrictions as per step 9.  Enter the API key in SimpleMap and try to add a location.  The longitude and latitude will not get populated.  Now remove the Application Restrictions for your key and update the location you added.  The longitude and latitude should now be populated.

**Comment by wpsmort** [comment]
We found that this works if you use HTTPS for the URL in the Application Restrictions on Google's Cloud Console.  It doesn't work if you use HTTP.

@arnaudbroes Please confirm this and update the docs.

**Comment by arnaudbroes** [comment]
This happens because the plugin is now calling Google's API over HTTPS. I've adjusted the documentation accordingly.
