### ISSUE TITLE
International Zip Codes Not Matching Correct Locations

### ISSUE THREAD

**Issue by philmccollam** [semperfiwebdesign/simplemap#293]
Hello — We are using the SimpleMap plugin for our international markets, and have started running into issues with the zip / postal code search field not searching in the correct locations.

Example: We have a location in Wien (Vienna), Austria — postal code 1110. When the user types 1110 into the search form, it returns the 'no results' response and moves the map to the opposite side of the country. However, if a visitor searches for Wien, the search results for the city and within the search radius appear without any issue. We've also double-checked that the postal codes are correct (no spaces or extra characters); we've tried creating a new location with the same settings, uploading the location as a CSV, and editing the location directly.

This is an error we've also found in two other countries (at the moment): France and Taiwan.

As mentioned, the search works fine for City, but fails with the zip / postal code.

Please let me know if you need any other information.

Thanks.

**Comment by wpsmort** [comment]
This is not a support forum, it is a development repository.  

This is not a bug with SimpleMap, this is because searching for 1110 does not provide Google Maps enough information to return results.  You need to provide more information in the search such as city and postal code.
