### ISSUE TITLE
Verify we're enqueuing scripts using the correct method

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#44]
This is in relation to Premium Support Forum post here - http://support.simplemap-plugin.com/discussions/problems/2478-map-not-loading

Specifically, the map is broken because of a jQuery issue in the custom theme. The developer of the custom theme responded with this:

Our theme can't use the default jquery provided by WordPress, and we have de-registered this one and registered a new one from CDN using the same key "jquery"

The issue with the SimpleMap plugin is because they enqueue the scripts using the "template_redirect" hook, which is run right after our deregistered hook is placed, so the script has as dependency the "jquery" file, and because of the step of execution there is no "jquery" on the dependency manager, so their scripts are not enqueued

This is not best WordPress practice, you should use proper hooks

**Comment by michaeltorbert** [comment]
I'll need a copy of the theme.

**Comment by wpsmort** [comment]
The pull request is tested and is good. I found no problems with the front end or the back end. I checked the browser console on each page for errors and found none.
