### ISSUE TITLE
Fix bug with location results separator

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#57]
See screenshot below:

<img width="993" alt="screen-capture" src="https://cloud.githubusercontent.com/assets/17548525/16096772/7b101298-3318-11e6-89d0-5efa2dc2a6d0.png">

First reported by RockTape (rocktape.com/us/find-retailer/)

**Comment by michaeltorbert** [comment]
<img width="956" alt="screen shot 2016-06-16 at 10 45 20 am" src="https://cloud.githubusercontent.com/assets/17364998/16120998/7a94b8d6-33af-11e6-8998-5a4524b61810.png">

**Comment by michaeltorbert** [comment]
<img width="513" alt="screen shot 2016-06-16 at 10 48 10 am" src="https://cloud.githubusercontent.com/assets/17364998/16121094/df59644c-33af-11e6-9dfb-ebc6a61ad596.png">

**Comment by wpsmort** [comment]
This is fixed.
