### ISSUE TITLE
Limit which users can add/edit/delete locations

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#58]
Currently, all user roles can add a new location. We need to have the same role restrictions as with any other post type.

**Comment by wpsmort** [comment]
I have verified that the correct user levels can perform the correct tasks.

A Subscriber cannot see SimpleMap in the admin.
A Contributor cannot see SimpleMap in the admin.
An Author can add, publish and edit their own location only.
An Editor can add, publish and edit others locations.

**Comment by michaeltorbert** [comment]
Is this something fixed or something never broken?

**Comment by wpsmort** [comment]
It was never broken to begin with.
