### ISSUE TITLE
menus

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/simplemap#66]
Instead of adding CPT and taxonomy menus to ours, why not add ours to theirs?

**Comment by michaeltorbert** [comment]
For this and #116, we can either 1) keep menus the same and do some trickery so that locations CPT menu expands or else 2) add our stuff to the built-in (but currently hidden) CTP menu.
Option 2 would mean that options pages aren't at the top and general options isn't the default page. This *may be able to be changed.

**Comment by wpsmort** [comment]
This is tested and is good.
