### ISSUE TITLE
Remove Auto-Detect Location by IP Address option

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#68]
The service we use for IP geolocation has shut down - http://www.telize.com/

We urgently need to remove this option from the plugin. Anyone currently using IP Address for Auto-Detect Location has a broken map which has resulted in a lot of support forum posts and emails.

We will eventually need to find a replacement free IP geolocation service. See issue #20 

<img width="829" alt="screenshot" src="https://cloud.githubusercontent.com/assets/17548525/16159925/670bbe88-3493-11e6-9003-8b18243e2a31.png">

**Comment by michaeltorbert** [comment]
This is fixed and should work with the freegeoip service

**Comment by wpsmort** [comment]
This is tested and works.
