### ISSUE TITLE
Scrollbar on map bubble doesn't appear in Chrome and Safari

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#76]
There is a known issue with the overflow scroll bar not showing in Chrome and Safari - https://www.sitepoint.com/community/t/vert-scroll-bar-for-overflow-auto-not-working-in-chrome/7615

This is a bug webkit.  

The article above has workarounds for this which we should look at.

**Comment by michaeltorbert** [comment]
@wpsmort Is this fixed? It works for me in Chrome.

**Comment by wpsmort** [comment]
This is fixed for me in Chrome and Safari on Mac.

@arnaudbroes Can you test in Chrome and Safari on Windows and see if the vertical scroll bar works on the map bubbles.  If it does then I think we can close this issue.

**Comment by arnaudbroes** [comment]
@wpsmort 
I can confirm this works for me on a test site.
I'll close the issue.
