### ISSUE TITLE
Fix the upload directory 

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/simplemap#8]
Fix the upload directory - http://wordpress.org/support/topic/plugin-simplemap-store-locator-fix-suggestion-for-import-directory

**Comment by wpsmort** [comment]
@michaeltorbert:  I tested this and found two issues:

1). I couldn't find the temp location of the import file on my local Pressmatic machine. I can see where it's supposed to be from the code but that location doesn't get created.
2). The import doesn't complete, probably related to #1 above.  It shows the locations in the table on  Step 1 but nothing happens on Step 2, all I get is the screen shown below:

<img width="1289" alt="screen shot 2017-01-20 at 12 11 36 pm" src="https://cloud.githubusercontent.com/assets/17548525/22158302/9e1ba566-df09-11e6-87b8-363ec8cb8325.png">

I'd like to recommend that the import file be temporarily stored in /wp-content/uploads

**Comment by wpsmort** [comment]
We have fixed the issues that were breaking the import and it is now working.

Need to test the fallback if the uploads directory doesn't exist.

**Comment by wpsmort** [comment]
The fallback works if uploads is not writeable.
