### ISSUE TITLE
Improve screenshots, including mobile

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/simplemap#82]
Something like this https://ps.w.org/simple-map/assets/screenshot-3.png?rev=1280197

**Comment by arnaudbroes** [comment]
@michaeltorbert are these for this page?
https://nl.wordpress.org/plugins/simplemap/screenshots/

**Comment by michaeltorbert** [comment]
Yep. :)

**Comment by arnaudbroes** [comment]
Related to #177.
