### ISSUE TITLE
Google now needs an API key

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#84]
SimpleMap users started complaining of issues with performing searched.   Upon investigation it appears that Google changed the requirements for accessing their API and now you have to have an API key - https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by michaeltorbert** [comment]
@wpsmort I think it can still use some improvement, but this works if they enter an API key.

**Comment by michaeltorbert** [comment]
@wpsmort This is marked as needs testing for 2.4.10... did we complete this?

**Comment by wpsmort** [comment]
This is completed and tested and was released in v2.4.10.  It's been working fine since then.
