### ISSUE TITLE
Fix the permalink refresh issue & flush code optimization

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/simplemap#9]
Fix the permalink refresh issue when you enable location permalinks

**Comment by michaeltorbert** [comment]
@wpsmort What is this issue?

**Comment by wpsmort** [comment]
@michaeltorbert This was an issue where, when you enabled the Location permalinks option under Optional / Experimental Features, we weren't flushing the permalinks so when you tried to go to a single location you got a 404 error.

This now appears to be fixed though.  I tested on a brand new site and it's flushing the permalinks.

**Comment by michaeltorbert** [comment]
Ok so the behavior was that when you change the location permalink, it took an extra page refresh for them to get flushed. It now should happen on the first pageload after changing.

**Comment by michaeltorbert** [comment]
@wpsmort  When testing, verify the issue first in the live version, since you weren't seeing it before.

**Comment by wpsmort** [comment]
This is tested and is confirmed fixed.
