### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by mashoodahmad123** [semperfiwebdesign/simplemap#90]
HI

I am getting problem in your plugin. Actually we changed the hosting server so we upload everything on new server. Every thing is working perfect except to your plugin.

Actually your site map plugin working fine on my old server and also working fine on my local machine but not working on new(current) server. we have checked everything twice and all configratuion same.

Can you plz let me know whats the issue so we can working this plugin here.

Thanks

**Comment by wpsmort** [comment]
Please use the support forums for support questions.  We will not respond to support questions posted on Github.
