### ISSUE TITLE
New searches do not close map bubbles previously opened

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#92]
When you perform a search and click on a map marker to display the bubble for that location, then perform a new search, the map bubble from the previous search is still open.

This was first reported by Greg Montano by email on 07/18/2016.

**Comment by contactashish13** [comment]
@wpsmort @michaeltorbert PR: https://github.com/semperfiwebdesign/simplemap/pull/217

**Comment by wpsmort** [comment]
This is tested and confirmed to fix the bug. Now when you perform a search, it closes any map bubbles that were previously opened.
