### ISSUE TITLE
Location importer no longer applies categories or tags

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/simplemap#98]
In version 2.4.9 we broke the Location Importer so that when you import locations with categories or tags, the categories and tags no longer get applied to the locations.  Instead all categories and tags have zero posts.  This worked fine prior to v2.4.9

First reported in the SimpleMap Premium Support forum here - http://support.simplemap-plugin.com/discussions/problems/2552-plugin-import-not-catching-the-categories-properly

**Comment by michaeltorbert** [comment]
@arnaudbroes Can you figure out which commit caused this to break? It probably happened sometime around the June 13 or June 14 commits https://github.com/semperfiwebdesign/simplemap/commits/master

**Comment by DeFeNdog** [comment]
I found that the $term variable was not set on line 482 of import-export.php (scope issue?).

I was able to correct the problem by swapping out $term->name to $name.

	From:
	wp_set_object_terms( $id, $term->name, $taxonomy, true );

	To:
	wp_set_object_terms( $id, $name, $taxonomy, true );

Hope this helps!

**Comment by arnaudbroes** [comment]
@michaeltorbert 
This commit broke it:
https://github.com/semperfiwebdesign/simplemap/commit/fafb4069f80f30fa6ab74b7ae36bdd773061e724

![image](https://cloud.githubusercontent.com/assets/18156697/22164065/dd29ea50-df55-11e6-9419-d507416902c8.png)

**Comment by wpsmort** [comment]
@michaeltorbert: I tested this and found that it does not preserve category hierarchy.  However, this is not new, this was broken prior to v2.4.9 and may have never worked.  I'll open a new issue for this and see if we can tell if it ever worked.

**Comment by wpsmort** [comment]
Opened new issue #131 to look at this.  Closing this issue as the importer works just like it did in version 2.4.8 (before we broke it).
